version: '3'
services: 
    server:
        build: .
        ports:
            - "8080:8080"
        environment: 
            - DB_CONN=root:dev@(127.0.0.1:3306)/domains?charset=utf8
    web:
        build: ./frontend
        ports:
            - "80:8090"
