version: "3"
services:
  server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_CONN=root:dev@(mysql8.0:3306)/domains?charset=utf8&parseTime=true
  web:
    build:
      context: ./frontend
      args:
        serverurl: http://localhost:8080
    ports:
      - "8090:80"
networks:
  default:
    external:
      name: dev-network
