version: "3"
services:
  server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_CONN=root:root@(db:3306)/domains?charset=utf8&parseTime=true
  web:
    build:
      context: ./frontend
      args:
        serverurl: http://localhost:8080
    ports:
      - "8090:80"
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: domains
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "6033:3066"
    volumes: 
      - "./db_data:/var/lib/mysql"

#networks:
#  default:
#    external:
#      name: dev-network
